made the textView scrollable

diff --git a/proj/viewmd/Makefile b/proj/viewmd/Makefile
--- a/proj/viewmd/Makefile
+++ b/proj/viewmd/Makefile
@@ -13,7 +13,7 @@ GLIB_COMPILE_RESOURCES = $(shell $(PKGCONFIG) --variable=glib_compile_resources 
 # Define the source and header directories
 SRC_DIR = src
 BUILT_SRC = $(SRC_DIR)/resources.c
-UI_DIR = $(SRC_DIR)/ui 
+UI_DIR = $(SRC_DIR)/ui
 
 # Get a list of all the source files
 SOURCES = $(wildcard $(SRC_DIR)/*.c)
@@ -25,13 +25,13 @@ HEADERS = $(wildcard $(SRC_DIR)/*.h)
 OBJECTS = $(SOURCES:.c=.o) $(BUILT_SRC:.c=.o)
 
 # Generated by bear
-COMPILE_CMDS = compile_commands.json
+COMPILE_CMDS_JSON = compile_commands.json
 
 # UI builder files
 G_RSC = $(SRC_DIR)/$(TARGET).gresource.xml
-UI = $(wildcard $(UI_DIR)/*.ui) 
+UI = $(wildcard $(UI_DIR)/*.ui)
 
-.PHONY: all clean cleanall build bear
+.PHONY: all clean cleanall build bear run
 
 # Define the default target
 all: $(TARGET)
@@ -47,14 +47,14 @@ $(BUILT_SRC): $(G_RSC) $(UI)
 $(TARGET): $(OBJECTS)
 	$(CC) -o $(@F) $(OBJECTS) $(LIBS)
 
-run: $(TARGET)
-	./$(TARGET) &
+# Define a target to run the executable
+run: bear
+	./$(TARGET)
 
-build: bear
-
+# Creates a compile_commands.json file for use with clangd
 bear:
-	bear -- make
-	make clean
+	@bear -- make -s > /dev/null || echo "bear FAILED: Is it installed?"
+	@$(MAKE) -s clean
 
 # Define a target to clean up generated files
 clean:
@@ -66,7 +66,7 @@ cleanall:
 	rm -f $(TARGET)
 	rm -f $(OBJECTS)
 	rm -f $(BUILT_SRC)
-	rm -f $(COMPILE_CMDS)
+	rm -f $(COMPILE_CMDS_JSON)
 
 debug-make:
 	@echo "SOURCES: $(SOURCES)"
@@ -89,8 +89,8 @@ debug-make:
 # Automatic Variables:
 # --------------------
 # $^ : Get list of all prerequisites
-# $< : Get first prerequisite 
+# $< : Get first prerequisite
 # $@ : Get target value
-# 
+#
 # gcc `pkg-config --cflags gtk+-3.0` -o main main.c `pkg-config --libs gtk+-3.0`
 # glib-compile-resources .gresource.xml --target=source/resources.c --generate-source
